services:
  bot:
    image: ghcr.io/tancred423/paissa-house-discord-bot:${DEPLOYMENT_HASH}
    container_name: paissa-house-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REGISTER_COMMANDS=false
      - DEPLOYMENT_HASH=${DEPLOYMENT_HASH:-}
      - ENVIRONMENT=production
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
    name: mysql-network
